### ISSUE TITLE
AutoSSH - Local Forward Tunnel

### ISSUE THREAD

**Issue by Bierchermuesli** [ThomDietrich/home-assistant-addons#19]
Hey, I like your addon!

I used the Tunnel for both ways to access a remote SQL and InfluxDB.  So I put `-N  -L 3306:100.66.66.12:3306 -L 8086:100.66.66.2:8086` to `other_ssh_options` and set 127.0.0.1 to db_url and influx connection. I know its a bit hacky but pretty simple usage as its in use in small remote hut with weak connection. 

It worked very well until 'recently'. It looks like the ports arn't exposed anymore, inside the container it works. Alltrought I don't see any breaking changes but didn't digged into it. Any advice? or idea for improovment?

**Comment by ThomDietrich** [comment]
Servus, thanks happy to hear you find it useful.
Your use case riddles me. With a `-L` forwarding you bind those sockets locally to the addon container. You would need additional configuration to make those globally accessible. It may be, that the default HA OS setup had weird and insecure defaults to allow this and that was recently changed with an update!?
Did you try explicitly setting the local interface? E.g. `-L 172.30.32.1:3306:100.66.66.12:3306`

**Comment by ThomDietrich** [comment]
Hey there! Did you spend any more time on this? I'll close the ticket for now but we can reopen if you have an idea how to improve this project ;)

**Comment by Bierchermuesli** [comment]
sorry for my missing feedback. I ended up with a total different setup. But I still tihink this is a nead hack :)

Thanks for you add-on!

**Comment by Marwe** [comment]
I have a similar use case, but for additional reverse port forwarding. I tried with the following (to forward paperless API, too), but it seems not to work due to the built up command line (see below)
```
-R 127.0.0.1:38124:172.30.32.1:8124
```

Two questions: how to state the (local) hostsystem, if possible by name, since the IP may change? I took it from the log and simply copied it.

The resulting commandline contains `-R 8123` from field `remote_forwarding`
```
[...]  -R 127.0.0.1:38123:172.30.32.1:8123 -R 8123 -v -N -R 127.0.0.1:38124:172.30.32.1:8124
```
An empty field `remote_forwarding` removes the additional `-R 8123` and yields the correct term `-R 127.0.0.1:38123:172.30.32.1:8123`, though the `8123` is not configured anywhere (maybe it is it the default?).

Thanks for the plugin :)

**Comment by ThomDietrich** [comment]
Hey @Marwe,

could you please post your addon configuration yaml?  Mine looks like this, which yields the intended results (judging by mosquitto):

```
hostname: autossh.xxx.de
ssh_port: 2244
username: homeassistant
remote_ip_address: 127.0.0.1
remote_port: 8003
other_ssh_options: "-N"
force_keygen: false
skip_remote_host_checks: false
remote_forwarding:
  - 192.168.192.10:1883:core-mosquitto:1883
  - 127.0.0.1:38124:172.30.32.1:8124
local_ip_address: home-assistant
local_port: 8123
```
